/*

	Create database Staging

*/


USE [master]
GO

/****** Object:  Database [Staging]    Script Date: 21/09/2023 8:40:29 pm ******/
CREATE DATABASE [Staging]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StageArea', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.DATAWAREHOUSE\MSSQL\DATA\StageArea.mdf' , SIZE = 9216KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ), 
 FILEGROUP [DATA] 
( NAME = N'StageArea_data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.DATAWAREHOUSE\MSSQL\DATA\StageArea_data.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%), 
 FILEGROUP [INDEX] 
( NAME = N'StageArea_index', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.DATAWAREHOUSE\MSSQL\DATA\StageArea_index.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'StageArea_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.DATAWAREHOUSE\MSSQL\DATA\StageArea_log.ldf' , SIZE = 17664KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Staging].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Staging] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Staging] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Staging] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Staging] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Staging] SET ARITHABORT OFF 
GO

ALTER DATABASE [Staging] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Staging] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Staging] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Staging] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Staging] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Staging] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Staging] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Staging] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Staging] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Staging] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Staging] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Staging] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Staging] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Staging] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Staging] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Staging] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Staging] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Staging] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Staging] SET  MULTI_USER 
GO

ALTER DATABASE [Staging] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Staging] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Staging] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Staging] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Staging] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Staging] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Staging] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Staging] SET  READ_WRITE 
GO