/*

	Create database Data_Vault

*/


USE [master]
GO

/****** Object:  Database [Data_Vault]    Script Date: 21/09/2023 8:45:26 pm ******/
CREATE DATABASE [Data_Vault]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DataVault', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.DATAWAREHOUSE\MSSQL\DATA\DataVault.mdf' , SIZE = 37888KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ), 
 FILEGROUP [ARCHIVE] 
( NAME = N'DataVault_archive', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.DATAWAREHOUSE\MSSQL\DATA\DataVault_archive.ndf' , SIZE = 5120000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%), 
 FILEGROUP [BUSINESS] 
( NAME = N'DataVault_business', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.DATAWAREHOUSE\MSSQL\DATA\DataVault_business.ndf' , SIZE = 1024000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024000KB ), 
 FILEGROUP [DATA] 
( NAME = N'DataVault_data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.DATAWAREHOUSE\MSSQL\DATA\DataVault_data.ndf' , SIZE = 1024000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240000KB ), 
 FILEGROUP [INDEX] 
( NAME = N'DataVault_index', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.DATAWAREHOUSE\MSSQL\DATA\DataVault_index.ndf' , SIZE = 1024000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'DataVault_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.DATAWAREHOUSE\MSSQL\DATA\DataVault_log.ldf' , SIZE = 1024000KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Data_Vault].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Data_Vault] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Data_Vault] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Data_Vault] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Data_Vault] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Data_Vault] SET ARITHABORT OFF 
GO

ALTER DATABASE [Data_Vault] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Data_Vault] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Data_Vault] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Data_Vault] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Data_Vault] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Data_Vault] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Data_Vault] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Data_Vault] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Data_Vault] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Data_Vault] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Data_Vault] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Data_Vault] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Data_Vault] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Data_Vault] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Data_Vault] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Data_Vault] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Data_Vault] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Data_Vault] SET RECOVERY BULK_LOGGED 
GO

ALTER DATABASE [Data_Vault] SET  MULTI_USER 
GO

ALTER DATABASE [Data_Vault] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Data_Vault] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Data_Vault] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Data_Vault] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Data_Vault] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Data_Vault] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Data_Vault] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Data_Vault] SET  READ_WRITE 
GO